import { signIn } from "@/auth";
import { AuthError } from "next-auth";
import { z } from "zod";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import postgres from "postgres";

const sql = postgres(process.env.POSTGRES_URL!, { ssl: "require" });

// This create the customer review to products.
export type State = {
  message: string;
  errors: {
    product_id?: string[];
    customer_name?: string[];
    customer_email?: string[];
    review_date?: string[];
    cust_review?: string[];
  };
};

function dbErrorMessage(error: unknown): string {
  const e = error as any;
  return (
    [e?.message, e?.code, e?.detail].filter(Boolean).join(" | ") ||
    "Unknown database error"
  );
}

export async function createReview(formData: any, customer_id: any) {
  const {
    product_id,
    customer_name,
    customer_email,
    review_date,
    cust_review,
  } = formData;

  const cust_rating = `0`;

  try {
    // seller_id is generated by Postgres DEFAULT (sequence)
    await sql`
        INSERT INTO product_customer (product_id, customer_id, cust_review, cust_rating, review_date)
        VALUES (${product_id}, ${customer_id}, ${cust_review}, ${cust_rating}, ${review_date}::date)
      `;
  } catch (error: unknown) {
    console.error("DB ERROR createReview:", error);
    return {
      errors: {},
      message: `Database Error: ${dbErrorMessage(error)}`,
    };
  }

  revalidatePath("/dashboard/sellers");
  redirect("/dashboard/sellers");
}

const CategoryEnum = z.enum(
  ["wood", "art", "christmas", "lamp_shades", "crochet", "knitwear"],
  { message: "Please select a category." },
);

export const productFormSchema = z.object({
  //   product_id: z.string(),
  product_name: z.string().min(1, { message: "Please enter a product name." }),
  product_price: z.string().min(1, { message: "Please enter a product name." }),
  product_image: z.string().min(1, { message: "Please enter a valid email." }),
  category: CategoryEnum,
  product_date: z.string().min(1, { message: "Please select a date." }),
  product_desc: z
    .string()
    .min(5, { message: "Please write at least 5 characters." }),
});
