import postgres from 'postgres';

const sql = postgres(process.env.POSTGRES_URL!, { ssl: 'require' });

/**
 * DB shape:
 * - seller_reviews.id is generated by Postgres (uuid_generate_v4())
 * - seller_reviews.seller_id is a FK that MUST equal sellers.id (also DB-generated)
 * - No manual ids are inserted for either sellers or reviews
 */

export type SellerReviewRow = {
  id: string; // review id (DB-generated UUID)
  seller_id: string; // FK -> sellers.id (DB-generated UUID)
  rating: number;
  comment: string | null;
  created_at: string;
  product_name: string | null;
  customer_name: string | null;
};

export type SellerReviewWithSellerName = SellerReviewRow & {
  seller_name: string;
};

/**
 * Call ONLY from seed/migrations (not during normal page requests).
 */
export async function ensureSellerReviewsTable() {
  await sql`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`;

  await sql`
    CREATE TABLE IF NOT EXISTS seller_reviews (
      id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
      seller_id UUID NOT NULL REFERENCES sellers(id) ON DELETE CASCADE,
      rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
      comment TEXT,
      created_at TIMESTAMP DEFAULT NOW(),
      product_name TEXT,
      customer_name TEXT
    );
  `;

  await sql`CREATE INDEX IF NOT EXISTS idx_seller_reviews_seller_id ON seller_reviews(seller_id);`;
  await sql`CREATE INDEX IF NOT EXISTS idx_seller_reviews_created_at ON seller_reviews(created_at);`;
}

/**
 * Fetch latest reviews for a seller (sellerId MUST be sellers.id from the DB).
 * Includes seller_name via JOIN.
 */
export async function fetchSellerReviewsBySellerId(sellerId: string) {
  if (!sellerId) return [];

  try {
    const data = await sql<SellerReviewWithSellerName[]>`
      SELECT
        r.id,
        r.seller_id,
        r.rating,
        r.comment,
        r.created_at,
        r.product_name,
        r.customer_name,
        s.seller_name
      FROM seller_reviews r
      JOIN sellers s ON s.id = r.seller_id
      WHERE r.seller_id = ${sellerId}::uuid
      ORDER BY r.created_at DESC
      LIMIT 50;
    `;
    return data;
  } catch (error) {
    console.error('Database Error (fetchSellerReviewsBySellerId):', error);
    return [];
  }
}

/**
 * Average rating for one seller.
 */
export async function fetchSellerAverageRating(sellerId: string) {
  if (!sellerId) return null;

  try {
    const rows = await sql<{ avg: number | null }[]>`
      SELECT AVG(rating)::float AS avg
      FROM seller_reviews
      WHERE seller_id = ${sellerId}::uuid;
    `;
    return rows[0]?.avg ?? null;
  } catch (error) {
    console.error('Database Error (fetchSellerAverageRating):', error);
    return null;
  }
}

/**
 counts.
 */
export async function fetchSellerReviewCount(sellerId: string) {
  if (!sellerId) return 0;

  try {
    const rows = await sql<{ count: number }[]>`
      SELECT COUNT(*)::int AS count
      FROM seller_reviews
      WHERE seller_id = ${sellerId}::uuid;
    `;
    return rows[0]?.count ?? 0;
  } catch (error) {
    console.error('Database Error (fetchSellerReviewCount):', error);
    return 0;
  }
}

export type CreateSellerReviewInput = {
  seller_id: string; // must be an existing sellers.id (UUID)
  rating: number; // 1..5
  comment?: string | null;
  product_name?: string | null;
  customer_name?: string | null;
};

/**
 * Create a review:
 * - does NOT accept or insert a manual review id
 * - Postgres generates seller_reviews.id and created_at
 */
export async function createSellerReview(input: CreateSellerReviewInput) {
  const {
    seller_id,
    rating,
    comment = null,
    product_name = null,
    customer_name = null,
  } = input;

  if (!seller_id) throw new Error('seller_id is required');
  if (!Number.isInteger(rating) || rating < 1 || rating > 5) {
    throw new Error('rating must be an integer between 1 and 5');
  }

  try {
    const [row] = await sql<SellerReviewRow[]>`
      INSERT INTO seller_reviews (seller_id, rating, comment, product_name, customer_name)
      VALUES (${seller_id}::uuid, ${rating}, ${comment}, ${product_name}, ${customer_name})
      RETURNING id, seller_id, rating, comment, created_at, product_name, customer_name;
    `;
    return row;
  } catch (error) {
    console.error('Database Error (createSellerReview):', error);
    throw error;
  }
}

/**
 * Delete a review by its DB-generated review id.
 */
export async function deleteSellerReviewById(reviewId: string) {
  if (!reviewId) return;

  try {
    await sql`DELETE FROM seller_reviews WHERE id = ${reviewId}::uuid;`;
  } catch (error) {
    console.error('Database Error (deleteSellerReviewById):', error);
    throw error;
  }
}
