'use server';

import { signIn } from '@/auth';
import { AuthError } from 'next-auth';
import { z } from 'zod';
import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import postgres from 'postgres';

const sql = postgres(process.env.POSTGRES_URL!, { ssl: 'require' });

const CategoryEnum = z.enum(
  ['wood', 'art', 'christmas', 'lamp_shades', 'crochet', 'knitwear'],
  { message: 'Please select a category.' },
);

const FormSchema = z.object({
  id: z.string(),
  sellerName: z.string().min(1, { message: 'Please enter a seller name.' }),
  category: CategoryEnum,
  email: z.string().email({ message: 'Please enter a valid email.' }),
  contact: z.string().min(1, { message: 'Please enter a contact number.' }),
  date: z.string().min(1, { message: 'Please select a date.' }),
  story: z.string().min(20, { message: 'Please write at least 20 characters.' }),
});

const CreateSeller = FormSchema.omit({ id: true });
const UpdateSeller = FormSchema.omit({ id: true });

export type State = {
  message: string;
  errors: {
    sellerName?: string[];
    category?: string[];
    email?: string[];
    contact?: string[];
    date?: string[];
    story?: string[];
  };
};

function dbErrorMessage(error: unknown): string {
  const e = error as any;
  return [e?.message, e?.code, e?.detail].filter(Boolean).join(' | ') || 'Unknown database error';
}

export async function createSeller(
  _prevState: State,
  formData: FormData,
): Promise<State> {
  const validatedFields = CreateSeller.safeParse({
    sellerName: formData.get('sellerName')?.toString(),
    category: formData.get('category')?.toString(),
    email: formData.get('email')?.toString(),
    contact: formData.get('contact')?.toString(),
    date: formData.get('date')?.toString(),
    story: formData.get('story')?.toString(),
  });

  if (!validatedFields.success) {
    return {
      errors: validatedFields.error.flatten().fieldErrors,
      message: 'Missing fields. Failed to create seller.',
    };
  }

  const { sellerName, category, email, contact, date, story } = validatedFields.data;

  try {
    // seller_id is generated by Postgres DEFAULT (sequence)
    await sql`
      INSERT INTO sellers (seller_name, category, email, contact_no, created_at, story)
      VALUES (${sellerName}, ${category}, ${email}, ${contact}, ${date}::date, ${story})
    `;
  } catch (error: unknown) {
    console.error('DB ERROR createSeller:', error);
    return {
      errors: {},
      message: `Database Error: ${dbErrorMessage(error)}`,
    };
  }

  revalidatePath('/dashboard/sellers');
  redirect('/dashboard/sellers');
}

export async function updateSeller(
  id: string,
  _prevState: State,
  formData: FormData,
): Promise<State> {
  const validatedFields = UpdateSeller.safeParse({
    sellerName: formData.get('sellerName')?.toString(),
    category: formData.get('category')?.toString(),
    email: formData.get('email')?.toString(),
    contact: formData.get('contact')?.toString(),
    date: formData.get('date')?.toString(),
    story: formData.get('story')?.toString(),
  });

  if (!validatedFields.success) {
    return {
      errors: validatedFields.error.flatten().fieldErrors,
      message: 'Missing fields. Failed to update seller.',
    };
  }

  const { sellerName, category, email, contact, date, story } = validatedFields.data;

  try {
    // IMPORTANT: we do NOT update seller_id (it stays permanent)
    await sql`
      UPDATE sellers
      SET seller_name = ${sellerName},
          category = ${category},
          email = ${email},
          contact_no = ${contact},
          created_at = ${date}::date,
          story = ${story}
      WHERE id = ${id}
    `;
  } catch (error: unknown) {
    console.error('DB ERROR updateSeller:', error);
    return {
      errors: {},
      message: `Database Error: ${dbErrorMessage(error)}`,
    };
  }

  revalidatePath('/dashboard/sellers');
  redirect('/dashboard/sellers');
}

export async function deleteSeller(id: string): Promise<void> {
  try {
    await sql`
      DELETE FROM sellers
      WHERE id = ${id}
    `;
  } catch (error: unknown) {
    console.error('DB ERROR deleteSeller:', error);
    throw new Error(`Database Error: ${dbErrorMessage(error)}`);
  }

  revalidatePath('/dashboard/sellers');
}

export async function authenticate(
  _prevState: string | undefined,
  formData: FormData,
) {
  try {
    await signIn('credentials', formData);
  } catch (error: unknown) {
    if (error instanceof AuthError) {
      switch (error.type) {
        case 'CredentialsSignin':
          return 'Invalid credentials.';
        default:
          return 'Something went wrong.';
      }
    }
    throw error;
  }
}
