'use server';

import { signIn } from '@/auth';
import { AuthError } from 'next-auth';
import { z } from 'zod';
import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import postgres from 'postgres';
import bcrypt from 'bcrypt';
import { ADMIN_EMAIL, normalizeEmail } from '@/app/lib/auth-constants';

const sql = postgres(process.env.POSTGRES_URL!, { ssl: 'require' });

const CategoryEnum = z.enum(
  ['wood', 'art', 'christmas', 'home', 'crochet-knitted'],
  { message: 'Please select a category.' },
);

/**
 * NOTE:
 * - sellers.id is generated by Postgres (UUID DEFAULT uuid_generate_v4()).
 * - We never accept or insert id from the client.
 * - created_at is generated by Postgres (DEFAULT NOW()) and we do not set it from the form.
 */
const FormSchema = z.object({
  sellerName: z.string().min(1, { message: 'Please enter a seller name.' }),
  category: CategoryEnum,
  email: z.string().email({ message: 'Please enter a valid email.' }),
  contact: z.string().min(1, { message: 'Please enter a contact number.' }),
  story: z.string().min(20, { message: 'Please write at least 20 characters.' }),
  imageUrl: z
    .string()
    .trim()
    .optional()
    .refine(
      (v) => !v || v.startsWith('/') || v.startsWith('http://') || v.startsWith('https://'),
      { message: 'Image URL must start with / or http(s)://' },
    )
    .transform((v) => (v && v.length > 0 ? v : null)), // ✅ always string | null
});

type FormFields = z.infer<typeof FormSchema>;

export type State = {
  message: string;
  errors: {
    sellerName?: string[];
    category?: string[];
    email?: string[];
    contact?: string[];
    story?: string[];
    imageUrl?: string[];
    password?: string[];
    confirmPassword?: string[];
  };
};

function validatePasswordPair(
  passwordRaw: FormDataEntryValue | null,
  confirmRaw: FormDataEntryValue | null,
  required: boolean,
) {
  const password = String(passwordRaw ?? '').trim();
  const confirmPassword = String(confirmRaw ?? '').trim();
  const errors: State['errors'] = {};

  if (required && !password) {
    errors.password = ['Password is required.'];
  }

  const hasAny = password.length > 0 || confirmPassword.length > 0;
  if (!required && !hasAny) {
    return { errors, password: null as string | null };
  }

  if (!password) {
    errors.password = ['Password is required.'];
  }

  if (!confirmPassword) {
    errors.confirmPassword = ['Please confirm the password.'];
  }

  if (password && password.length < 8) {
    errors.password = ['Password must be at least 8 characters.'];
  }

  if (password && confirmPassword && password !== confirmPassword) {
    errors.confirmPassword = ['Passwords do not match.'];
  }

  if (Object.keys(errors).length > 0) {
    return { errors, password: null as string | null };
  }

  return { errors: {}, password };
}

function dbErrorMessage(error: unknown): string {
  const e = error as any;
  return (
    [e?.message, e?.code, e?.detail].filter(Boolean).join(' | ') ||
    'Unknown database error'
  );
}

/* ------------------------- SELLERS ACTIONS ------------------------- */

export async function createSeller(
  _prevState: State,
  formData: FormData,
): Promise<State> {
  const validatedFields = FormSchema.safeParse({
    sellerName: formData.get('sellerName')?.toString(),
    category: formData.get('category')?.toString(),
    email: formData.get('email')?.toString(),
    contact: formData.get('contact')?.toString(),
    story: formData.get('story')?.toString(),
    imageUrl: formData.get('imageUrl')?.toString(), // ✅ transform handles empty -> null
  });

  if (!validatedFields.success) {
    return {
      errors: validatedFields.error.flatten().fieldErrors,
      message: 'Missing fields. Failed to create seller.',
    };
  }

  const passwordValidation = validatePasswordPair(
    formData.get('password'),
    formData.get('confirmPassword'),
    true,
  );
  if (Object.keys(passwordValidation.errors).length > 0 || !passwordValidation.password) {
    return {
      errors: passwordValidation.errors,
      message: 'Password validation failed.',
    };
  }

  const { sellerName, category, email, contact, story, imageUrl } =
    validatedFields.data as FormFields;
  const normalizedEmail = normalizeEmail(email);

  if (normalizedEmail === ADMIN_EMAIL) {
    return {
      errors: { email: ['Seller email cannot use the admin email address.'] },
      message: 'Invalid seller email.',
    };
  }

  try {
    const hashedPassword = await bcrypt.hash(passwordValidation.password, 10);

    await sql.begin(async (tx) => {
      await tx`
        INSERT INTO sellers (seller_name, category, email, contact_no, story, image_url)
        VALUES (
          ${sellerName},
          ${category},
          ${normalizedEmail},
          ${contact},
          ${story},
          ${imageUrl}
        )
      `;

      await tx`
        INSERT INTO users (name, email, password)
        VALUES (${sellerName}, ${normalizedEmail}, ${hashedPassword})
        ON CONFLICT (email) DO UPDATE
        SET
          name = EXCLUDED.name,
          password = EXCLUDED.password
      `;
    });
  } catch (error: unknown) {
    console.error('DB ERROR createSeller:', error);
    return { errors: {}, message: `Database Error: ${dbErrorMessage(error)}` };
  }

  revalidatePath('/dashboard/sellers');
  redirect('/dashboard/sellers');
}

export async function updateSeller(
  id: string,
  _prevState: State,
  formData: FormData,
): Promise<State> {
  const validatedFields = FormSchema.safeParse({
    sellerName: formData.get('sellerName')?.toString(),
    category: formData.get('category')?.toString(),
    email: formData.get('email')?.toString(),
    contact: formData.get('contact')?.toString(),
    story: formData.get('story')?.toString(),
    imageUrl: formData.get('imageUrl')?.toString(), // transform handles empty -> null
  });

  if (!validatedFields.success) {
    return {
      errors: validatedFields.error.flatten().fieldErrors,
      message: 'Missing fields. Failed to update seller.',
    };
  }

  const passwordValidation = validatePasswordPair(
    formData.get('password'),
    formData.get('confirmPassword'),
    false,
  );
  if (Object.keys(passwordValidation.errors).length > 0) {
    return {
      errors: passwordValidation.errors,
      message: 'Password validation failed.',
    };
  }

  const { sellerName, category, email, contact, story, imageUrl } =
    validatedFields.data as FormFields;
  const newEmail = normalizeEmail(email);

  if (newEmail === ADMIN_EMAIL) {
    return {
      errors: { email: ['Seller email cannot use the admin email address.'] },
      message: 'Invalid seller email.',
    };
  }

  try {
    const passwordHash = passwordValidation.password
      ? await bcrypt.hash(passwordValidation.password, 10)
      : null;

    await sql.begin(async (tx) => {
      const currentRows = await tx<{ email: string }[]>`
        SELECT email
        FROM sellers
        WHERE id = ${id}::uuid
        LIMIT 1
      `;

      const currentSeller = currentRows[0];
      if (!currentSeller) {
        throw new Error('Seller not found.');
      }

      const oldEmail = normalizeEmail(currentSeller.email);

      await tx`
        UPDATE sellers
        SET seller_name = ${sellerName},
            category = ${category},
            email = ${newEmail},
            contact_no = ${contact},
            story = ${story},
            image_url = ${imageUrl}
        WHERE id = ${id}::uuid
      `;

      const movedUser = passwordHash
        ? await tx<{ id: string }[]>`
            UPDATE users
            SET email = ${newEmail},
                name = ${sellerName},
                password = ${passwordHash}
            WHERE LOWER(email) = ${oldEmail}
            RETURNING id
          `
        : await tx<{ id: string }[]>`
            UPDATE users
            SET email = ${newEmail},
                name = ${sellerName}
            WHERE LOWER(email) = ${oldEmail}
            RETURNING id
          `;

      if (movedUser.length > 0) return;

      if (!passwordHash) {
        throw new Error(
          'No linked login user found for this seller. Provide a new password to link one.',
        );
      }

      await tx`
        INSERT INTO users (name, email, password)
        VALUES (${sellerName}, ${newEmail}, ${passwordHash})
        ON CONFLICT (email) DO UPDATE
        SET
          name = EXCLUDED.name,
          password = EXCLUDED.password
      `;
    });
  } catch (error: unknown) {
    console.error('DB ERROR updateSeller:', error);
    if (
      error instanceof Error &&
      error.message.includes('No linked login user found for this seller')
    ) {
      return {
        errors: {
          password: ['Set a new password to create a linked login for this seller.'],
        },
        message: error.message,
      };
    }
    return { errors: {}, message: `Database Error: ${dbErrorMessage(error)}` };
  }

  revalidatePath('/dashboard/sellers');
  redirect('/dashboard/sellers');
}

export async function deleteSeller(id: string): Promise<void> {
  try {
    await sql`DELETE FROM sellers WHERE id = ${id}::uuid`;
  } catch (error: unknown) {
    console.error('DB ERROR deleteSeller:', error);
    throw new Error(`Database Error: ${dbErrorMessage(error)}`);
  }

  revalidatePath('/dashboard/sellers');
  redirect('/dashboard/sellers');
}

/* ------------------------- AUTH ACTION ------------------------- */

export async function authenticate(
  _prevState: string | undefined,
  formData: FormData,
) {
  try {
    await signIn('credentials', formData);
  } catch (error: unknown) {
    if (error instanceof AuthError) {
      switch (error.type) {
        case 'CredentialsSignin':
          return 'Invalid credentials.';
        default:
          return 'Something went wrong.';
      }
    }
    throw error;
  }
}
