'use server';

import { signIn } from '@/auth';
import { AuthError } from 'next-auth';
import { z } from 'zod';
import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import postgres from 'postgres';

const sql = postgres(process.env.POSTGRES_URL!, { ssl: 'require' });

const CategoryEnum = z.enum(
  ['wood', 'art', 'christmas', 'home', 'crochet', 'knitwear'],
  { message: 'Please select a category.' },
);

/**
 * NOTE:
 * - sellers.id is generated by Postgres (UUID DEFAULT uuid_generate_v4()).
 * - We never accept or insert id from the client.
 * - created_at is generated by Postgres (DEFAULT NOW()) and we do not set it from the form.
 */
const FormSchema = z.object({
  sellerName: z.string().min(1, { message: 'Please enter a seller name.' }),
  category: CategoryEnum,
  email: z.string().email({ message: 'Please enter a valid email.' }),
  contact: z.string().min(1, { message: 'Please enter a contact number.' }),
  story: z.string().min(20, { message: 'Please write at least 20 characters.' }),
  imageUrl: z
    .string()
    .trim()
    .optional()
    .refine(
      (v) => !v || v.startsWith('/') || v.startsWith('http://') || v.startsWith('https://'),
      { message: 'Image URL must start with / or http(s)://' },
    )
    .transform((v) => (v && v.length > 0 ? v : null)), // ✅ always string | null
});

type FormFields = z.infer<typeof FormSchema>;

export type State = {
  message: string;
  errors: {
    sellerName?: string[];
    category?: string[];
    email?: string[];
    contact?: string[];
    story?: string[];
    imageUrl?: string[];
  };
};

function dbErrorMessage(error: unknown): string {
  const e = error as any;
  return (
    [e?.message, e?.code, e?.detail].filter(Boolean).join(' | ') ||
    'Unknown database error'
  );
}

/* ------------------------- SELLERS ACTIONS ------------------------- */

export async function createSeller(
  _prevState: State,
  formData: FormData,
): Promise<State> {
  const validatedFields = FormSchema.safeParse({
    sellerName: formData.get('sellerName')?.toString(),
    category: formData.get('category')?.toString(),
    email: formData.get('email')?.toString(),
    contact: formData.get('contact')?.toString(),
    story: formData.get('story')?.toString(),
    imageUrl: formData.get('imageUrl')?.toString(), // ✅ transform handles empty -> null
  });

  if (!validatedFields.success) {
    return {
      errors: validatedFields.error.flatten().fieldErrors,
      message: 'Missing fields. Failed to create seller.',
    };
  }

  const { sellerName, category, email, contact, story, imageUrl } =
    validatedFields.data as FormFields;

  try {
    await sql`
      INSERT INTO sellers (seller_name, category, email, contact_no, story, image_url)
      VALUES (${sellerName}, ${category}, ${email}, ${contact}, ${story}, ${imageUrl})
    `;
  } catch (error: unknown) {
    console.error('DB ERROR createSeller:', error);
    return { errors: {}, message: `Database Error: ${dbErrorMessage(error)}` };
  }

  revalidatePath('/dashboard/sellers');
  redirect('/dashboard/sellers');
}

export async function updateSeller(
  id: string,
  _prevState: State,
  formData: FormData,
): Promise<State> {
  const validatedFields = FormSchema.safeParse({
    sellerName: formData.get('sellerName')?.toString(),
    category: formData.get('category')?.toString(),
    email: formData.get('email')?.toString(),
    contact: formData.get('contact')?.toString(),
    story: formData.get('story')?.toString(),
    imageUrl: formData.get('imageUrl')?.toString(), // ✅ transform handles empty -> null
  });

  if (!validatedFields.success) {
    return {
      errors: validatedFields.error.flatten().fieldErrors,
      message: 'Missing fields. Failed to update seller.',
    };
  }

  const { sellerName, category, email, contact, story, imageUrl } =
    validatedFields.data as FormFields;

  try {
    await sql`
      UPDATE sellers
      SET seller_name = ${sellerName},
          category = ${category},
          email = ${email},
          contact_no = ${contact},
          story = ${story},
          image_url = ${imageUrl}
      WHERE id = ${id}::uuid
    `;
  } catch (error: unknown) {
    console.error('DB ERROR updateSeller:', error);
    return { errors: {}, message: `Database Error: ${dbErrorMessage(error)}` };
  }

  revalidatePath('/dashboard/sellers');
  redirect('/dashboard/sellers');
}

export async function deleteSeller(id: string): Promise<void> {
  try {
    await sql`DELETE FROM sellers WHERE id = ${id}::uuid`;
  } catch (error: unknown) {
    console.error('DB ERROR deleteSeller:', error);
    throw new Error(`Database Error: ${dbErrorMessage(error)}`);
  }

  revalidatePath('/dashboard/sellers');
  redirect('/dashboard/sellers');
}

/* ------------------------- AUTH ACTION ------------------------- */

export async function authenticate(
  _prevState: string | undefined,
  formData: FormData,
) {
  try {
    await signIn('credentials', formData);
  } catch (error: unknown) {
    if (error instanceof AuthError) {
      switch (error.type) {
        case 'CredentialsSignin':
          return 'Invalid credentials.';
        default:
          return 'Something went wrong.';
      }
    }
    throw error;
  }
}

