import postgres from 'postgres';
import { SellerForm, SellersTableType } from './definitions';

const sql = postgres(process.env.POSTGRES_URL!, { ssl: 'require' });

const ITEMS_PER_PAGE = 6;

/**
 * IMPORTANT:
 * - sellers.id is the ONLY seller identifier (UUID generated by Postgres).
 * - There is NO seller_id column in sellers.
 */

export async function fetchSellers() {
  try {
    const sellers = await sql<SellersTableType[]>`
      SELECT
        id,
        seller_name,
        category,
        email,
        contact_no,
        created_at,
        story,
        image_url
      FROM sellers
      ORDER BY seller_name ASC
    `;
    return sellers;
  } catch (error) {
    console.error('Database Error:', error);
    throw new Error('Failed to fetch all sellers.');
  }
}

export async function fetchFilteredSellers(query: string, currentPage: number) {
  const offset = (currentPage - 1) * ITEMS_PER_PAGE;

  try {
    const sellers = await sql<SellersTableType[]>`
      SELECT
        id,
        seller_name,
        category,
        email,
        contact_no,
        created_at,
        story,
        image_url
      FROM sellers
      WHERE
        seller_name ILIKE ${`%${query}%`} OR
        category ILIKE ${`%${query}%`} OR
        email ILIKE ${`%${query}%`} OR
        contact_no ILIKE ${`%${query}%`} OR
        created_at::text ILIKE ${`%${query}%`} OR
        story ILIKE ${`%${query}%`}
      ORDER BY created_at DESC
      LIMIT ${ITEMS_PER_PAGE} OFFSET ${offset}
    `;
    return sellers;
  } catch (error) {
    console.error('Database Error:', error);
    throw new Error('Failed to fetch sellers.');
  }
}

export async function fetchSellersPages(query: string) {
  try {
    const data = await sql`
      SELECT COUNT(*)::int AS count
      FROM sellers
      WHERE
        seller_name ILIKE ${`%${query}%`} OR
        category ILIKE ${`%${query}%`} OR
        email ILIKE ${`%${query}%`} OR
        contact_no ILIKE ${`%${query}%`} OR
        created_at::text ILIKE ${`%${query}%`} OR
        story ILIKE ${`%${query}%`}
    `;

    const totalPages = Math.ceil(Number(data[0].count ?? 0) / ITEMS_PER_PAGE);
    return totalPages;
  } catch (error) {
    console.error('Database Error:', error);
    throw new Error('Failed to fetch total number of sellers.');
  }
}

export async function fetchSellerById(id: string) {
  if (!id) {
    throw new Error('fetchSellerById: id is required (received undefined/empty).');
  }

  try {
    const data = await sql<SellerForm[]>`
      SELECT
        id,
        seller_name,
        category,
        email,
        contact_no,
        created_at,
        story,
        image_url
      FROM sellers
      WHERE id = ${id}::uuid
      LIMIT 1;
    `;

    return data[0] ?? null;
  } catch (error) {
    console.error('Database Error (fetchSellerById):', error);
    throw new Error('Failed to fetch seller.');
  }
}

export async function fetchSellerByProductId(productId: string) {
  if (!productId) {
    throw new Error(
      'fetchSellerByProductId: productId is required (received undefined/empty).',
    );
  }

  try {
    const rows = await sql<SellerForm[]>`
      SELECT
        s.id,
        s.seller_name,
        s.category,
        s.email,
        s.contact_no,
        s.created_at,
        s.story,
        s.image_url
      FROM products p
      JOIN sellers s
        ON (
          s.id = p.seller_id
          OR (
            p.seller_id IS NULL
            AND LOWER(s.email) = LOWER(p.email)
          )
        )
      WHERE p.id = ${productId}::uuid
      LIMIT 1;
    `;

    return rows[0] ?? null;
  } catch (error) {
    console.error('Database Error (fetchSellerByProductId):', error);
    throw new Error('Failed to fetch seller for product.');
  }
}

/**
 * Sellers dashboard cards data
 * NOTE: Adjust table names to match your schema.
 * If using seller_reviews table, update the reviewCount query accordingly.
 */
export async function fetchSellerCardData() {
  try {
    const sellerCountPromise = sql`SELECT COUNT(*)::int AS count FROM sellers`;
    const productCountPromise = sql`SELECT COUNT(*)::int AS count FROM products`;
    const reviewCountPromise = sql`SELECT COUNT(*)::int AS count FROM seller_reviews`;

    const [sellerCount, productCount, reviewCount] = await Promise.all([
      sellerCountPromise,
      productCountPromise,
      reviewCountPromise,
    ]);

    const numberOfSellers = Number(sellerCount[0]?.count ?? 0);
    const numberOfProducts = Number(productCount[0]?.count ?? 0);
    const numberOfReviews = Number(reviewCount[0]?.count ?? 0);

    return {
      numberOfSellers,
      numberOfProducts,
      numberOfReviews,
    };
  } catch (error) {
    console.error('Database Error:', error);
    throw new Error('Failed to fetch seller card data.');
  }
}

